# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:50
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171118_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.product_image_path),
        ),
    ]
