# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171027_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category_directory_path),
        ),
    ]
