# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_search_string',
            field=models.TextField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
