# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:48
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_search_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=imagekit.models.fields.ProcessedImageField(upload_to=product.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.category_directory_path),
        ),
    ]
