# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productreview_productvisited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_duration',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Days'),
        ),
    ]
