# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_auto_20171105_0148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterWarrenty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_serial', models.CharField(db_index=True, max_length=100, verbose_name='Product Serial')),
                ('shop_name', models.CharField(db_index=True, max_length=50, verbose_name='Shop Name')),
                ('shop_address', models.TextField(blank=True, max_length=500, null=True)),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('warranty_expire_date', models.DateTimeField(editable=False, verbose_name='Expire Date')),
                ('warranty_status', models.CharField(choices=[('EX', 'EXPIRED'), ('VL', 'VALID')], max_length=3, verbose_name='Warranty Status')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
