# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warrenty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20171118_1450'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimProductWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_claim_subject', models.CharField(max_length=200)),
                ('claim_date', models.DateField(auto_now_add=True, verbose_name='Claim Date')),
                ('resolve_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Resolve Date')),
                ('warranty_details', models.TextField(blank=True, null=True)),
                ('claim_status', models.CharField(choices=[('4', 'CLAIMED'), ('5', 'REVIEWING'), ('6', 'REJECTED'), ('7', 'RESOLVED')], max_length=1, verbose_name='Claim Status')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterWarrenty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_serial', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Product Serial')),
                ('shop_name', models.CharField(db_index=True, max_length=50, verbose_name='Shop Name')),
                ('shop_address', models.TextField(blank=True, max_length=500, null=True)),
                ('purchase_date', models.DateField(editable=False, verbose_name='Purchase Date')),
                ('warranty_expire_date', models.DateField(editable=False, verbose_name='Expire Date')),
                ('warranty_status', models.CharField(choices=[('0', 'SUBMITTED'), ('1', 'ACCEPTED'), ('2', 'REJECTED'), ('3', 'WARRANTY EXPIRED'), ('4', 'WARRANTY CLAIMED'), ('5', 'CLAIM REVIEWING'), ('6', 'CLAIM REJECTED'), ('7', 'CLAIM RESOLVED')], max_length=1, verbose_name='Warranty Status')),
                ('warranty_card_image', models.ImageField(blank=True, null=True, upload_to=warrenty.models.warranty_card_directory_path)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='claimproductwarranty',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrenty.RegisterWarrenty'),
        ),
    ]
