# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import warrenty.models


class Migration(migrations.Migration):

    dependencies = [
        ('warrenty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerwarrenty',
            name='warranty_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=warrenty.models.warranty_card_directory_path),
        ),
    ]
