# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrenty', '0002_registerwarrenty_warranty_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerwarrenty',
            name='product_serial',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Product Serial'),
        ),
        migrations.AlterField(
            model_name='registerwarrenty',
            name='warranty_status',
            field=models.CharField(choices=[('0', 'SUBMITTED'), ('1', 'ACCEPTED'), ('2', 'REJECTED'), ('3', 'EXPIRED')], max_length=3, verbose_name='Warranty Status'),
        ),
    ]
