# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warrenty', '0004_auto_20171111_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimProductWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_claim_subject', models.CharField(max_length=200)),
                ('claim_date', models.DateField(auto_now_add=True, verbose_name='Claim Date')),
                ('resolve_date', models.DateField(editable=False, verbose_name='Resolve Date')),
                ('warranty_details', models.TextField(blank=True, null=True)),
                ('claim_status', models.CharField(choices=[('4', 'CLAIMED'), ('5', 'REVIEWING'), ('6', 'REJECTED'), ('7', 'RESOLVED')], max_length=1, verbose_name='Claim Status')),
            ],
        ),
        migrations.AlterField(
            model_name='registerwarrenty',
            name='purchase_date',
            field=models.DateField(editable=False, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='registerwarrenty',
            name='warranty_status',
            field=models.CharField(choices=[('0', 'SUBMITTED'), ('1', 'ACCEPTED'), ('2', 'REJECTED'), ('3', 'WARRANTY EXPIRED'), ('4', 'WARRANTY CLAIMED'), ('5', 'CLAIM REVIEWING'), ('6', 'CLAIM REJECTED'), ('7', 'CLAIM RESOLVED')], max_length=1, verbose_name='Warranty Status'),
        ),
        migrations.AddField(
            model_name='claimproductwarranty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrenty.RegisterWarrenty'),
        ),
    ]
