# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrenty', '0005_auto_20171112_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimproductwarranty',
            name='resolve_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Resolve Date'),
        ),
    ]
