# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warrenty', '0007_auto_20171113_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimproductwarranty',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warrenty.RegisterWarrenty'),
        ),
    ]
