# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innstaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='innstaluser',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Terms & Condition'),
        ),
        migrations.AlterField(
            model_name='innstaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='innstaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='innstaluser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='innstaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
    ]
