# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0002_auto_20171022_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innstaluser',
            name='terms',
        ),
    ]
