# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0003_remove_innstaluser_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='innstaluser',
            name='user_type',
            field=models.CharField(choices=[(0, 'Admin'), (1, 'Customer'), (2, 'BUSINESS')], default=1, max_length=1),
        ),
    ]
