# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usms.models


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0004_innstaluser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Package Name')),
                ('price', models.CharField(max_length=50, verbose_name='Package Cost')),
                ('duration', models.DurationField(blank=True, default=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_expire_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usms.Package')),
            ],
        ),
        migrations.AddField(
            model_name='innstaluser',
            name='is_active_subscription',
            field=models.BooleanField(default=False, editable=False, verbose_name='active subscription'),
        ),
        migrations.AlterField(
            model_name='innstaluser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=usms.models.avatar_directory_path),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
