# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0005_auto_20171027_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Package Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='package',
            field=models.ManyToManyField(related_name='package_service', to='usms.Package'),
        ),
    ]
