# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usms', '0007_auto_20171027_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='innstaluser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
